In [19]:
print("This week 3 assignment-Segmenting and Clustering Neighborhoods in Toronto")

This week 3 assignment-Segmenting and Clustering Neighborhoods in Toronto

In [20]:
import pandas as pd
import numpy as np

In [5]:
url="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

In [21]:
from lxml import *

In [46]:
data= pd.read_html(url)

In [48]:
data

[    Postcode           Borough          Neighbourhood
 0        M1A      Not assigned           Not assigned
 1        M2A      Not assigned           Not assigned
 2        M3A        North York              Parkwoods
 3        M4A        North York       Victoria Village
 4        M5A  Downtown Toronto           Harbourfront
 ..       ...               ...                    ...
 283      M8Z         Etobicoke              Mimico NW
 284      M8Z         Etobicoke     The Queensway West
 285      M8Z         Etobicoke  Royal York South West
 286      M8Z         Etobicoke         South of Bloor
 287      M9Z      Not assigned           Not assigned

 [288 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
283      M8Z         Etobicoke              Mimico NW
284      M8Z         Etobicoke     The Queensway West
285      M8Z         Etobicoke  Royal York South West
286      M8Z         Etobicoke         South of Bloor
287      M9Z      Not assigned           Not assigned

[288 rows x 3 columns]

In [55]:
data1=pd.DataFrame(data[0])

In [57]:
data1.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [58]:
data1["Postcode"]

0      M1A
1      M2A
2      M3A
3      M4A
4      M5A
      ...
283    M8Z
284    M8Z
285    M8Z
286    M8Z
287    M9Z
Name: Postcode, Length: 288, dtype: object

In [60]:
data1.dropna(subset=["Borough"],axis=0, inplace=True)

In [72]:
data2=data1.drop([0],axis=0)

In [73]:
data2

    Postcode           Borough          Neighbourhood
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
5        M5A  Downtown Toronto            Regent Park
..       ...               ...                    ...
283      M8Z         Etobicoke              Mimico NW
284      M8Z         Etobicoke     The Queensway West
285      M8Z         Etobicoke  Royal York South West
286      M8Z         Etobicoke         South of Bloor
287      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]

In [91]:
j=0
a=[]
for  i in data1["Borough"]:
    if("Not assigned" == i):
        a.append(j)
    j=j+1

In [118]:
data2=data1.drop(a,axis=0)

In [119]:
data2

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M5A  Downtown Toronto               Regent Park
6        M6A        North York          Lawrence Heights
..       ...               ...                       ...
282      M8Z         Etobicoke  Kingsway Park South West
283      M8Z         Etobicoke                 Mimico NW
284      M8Z         Etobicoke        The Queensway West
285      M8Z         Etobicoke     Royal York South West
286      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [120]:
data2.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [121]:
data2.describe()

       Postcode    Borough Neighbourhood
count       211        211           211
unique      103         11           209
top         M9V  Etobicoke     Runnymede
freq          8         45             2

In [133]:
data2.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [136]:
df3=data2
df3

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M5A  Downtown Toronto               Regent Park
6        M6A        North York          Lawrence Heights
..       ...               ...                       ...
282      M8Z         Etobicoke  Kingsway Park South West
283      M8Z         Etobicoke                 Mimico NW
284      M8Z         Etobicoke        The Queensway West
285      M8Z         Etobicoke     Royal York South West
286      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [146]:
df3.insert(loc=0,column="", value=np.arange(len(df3)))
df3

         Postcode           Borough             Neighbourhood
2      0      M3A        North York                 Parkwoods
3      1      M4A        North York          Victoria Village
4      2      M5A  Downtown Toronto              Harbourfront
5      3      M5A  Downtown Toronto               Regent Park
6      4      M6A        North York          Lawrence Heights
..   ...      ...               ...                       ...
282  206      M8Z         Etobicoke  Kingsway Park South West
283  207      M8Z         Etobicoke                 Mimico NW
284  208      M8Z         Etobicoke        The Queensway West
285  209      M8Z         Etobicoke     Royal York South West
286  210      M8Z         Etobicoke            South of Bloor

[211 rows x 4 columns]

In [147]:
df3.set_index("",inplace=True)

In [157]:
df3.head(60)

   Postcode           Borough        Neighbourhood

0       M3A        North York            Parkwoods
1       M4A        North York     Victoria Village
2       M5A  Downtown Toronto         Harbourfront
3       M5A  Downtown Toronto          Regent Park
4       M6A        North York     Lawrence Heights
5       M6A        North York       Lawrence Manor
6       M7A      Queen's Park         Not assigned
7       M9A         Etobicoke     Islington Avenue
8       M1B       Scarborough                Rouge
9       M1B       Scarborough              Malvern
10      M3B        North York      Don Mills North
11      M4B         East York     Woodbine Gardens
12      M4B         East York        Parkview Hill
13      M5B  Downtown Toronto              Ryerson
14      M5B  Downtown Toronto      Garden District
15      M6B        North York            Glencairn
16      M9B         Etobicoke           Cloverdale
17      M9B         Etobicoke            Islington
18      M9B         Etobicoke         Martin Grove
19      M9B         Etobicoke     Princess Gardens
20      M9B         Etobicoke      West Deane Park
21      M1C       Scarborough       Highland Creek
22      M1C       Scarborough           Rouge Hill
23      M1C       Scarborough           Port Union
24      M3C        North York      Flemingdon Park
25      M3C        North York      Don Mills South
26      M4C         East York     Woodbine Heights
27      M5C  Downtown Toronto       St. James Town
28      M6C              York   Humewood-Cedarvale
29      M9C         Etobicoke    Bloordale Gardens
30      M9C         Etobicoke             Eringate
31      M9C         Etobicoke        Markland Wood
32      M9C         Etobicoke    Old Burnhamthorpe
33      M1E       Scarborough            Guildwood
34      M1E       Scarborough          Morningside
35      M1E       Scarborough            West Hill
36      M4E      East Toronto          The Beaches
37      M5E  Downtown Toronto          Berczy Park
38      M6E              York  Caledonia-Fairbanks
39      M1G       Scarborough               Woburn
40      M4G         East York              Leaside
41      M5G  Downtown Toronto   Central Bay Street
42      M6G  Downtown Toronto             Christie
43      M1H       Scarborough            Cedarbrae
44      M2H        North York    Hillcrest Village
45      M3H        North York       Bathurst Manor
46      M3H        North York      Downsview North
47      M3H        North York       Wilson Heights
48      M4H         East York     Thorncliffe Park
49      M5H  Downtown Toronto             Adelaide
50      M5H  Downtown Toronto                 King
51      M5H  Downtown Toronto             Richmond
52      M6H      West Toronto   Dovercourt Village
53      M6H      West Toronto             Dufferin
54      M1J       Scarborough  Scarborough Village
55      M2J        North York             Fairview
56      M2J        North York           Henry Farm
57      M2J        North York               Oriole
58      M3J        North York       Northwood Park
59      M3J        North York      York University

In [163]:
a=[]
j=0
for i in df3["Neighbourhood"]:
    if("Not assigned" == i):
        df3["Neighbourhood"][j]=df3["Borough"][j]
    j=j+1
df3.head(20)

   Postcode           Borough     Neighbourhood

0       M3A        North York         Parkwoods
1       M4A        North York  Victoria Village
2       M5A  Downtown Toronto      Harbourfront
3       M5A  Downtown Toronto       Regent Park
4       M6A        North York  Lawrence Heights
5       M6A        North York    Lawrence Manor
6       M7A      Queen's Park      Queen's Park
7       M9A         Etobicoke  Islington Avenue
8       M1B       Scarborough             Rouge
9       M1B       Scarborough           Malvern
10      M3B        North York   Don Mills North
11      M4B         East York  Woodbine Gardens
12      M4B         East York     Parkview Hill
13      M5B  Downtown Toronto           Ryerson
14      M5B  Downtown Toronto   Garden District
15      M6B        North York         Glencairn
16      M9B         Etobicoke        Cloverdale
17      M9B         Etobicoke         Islington
18      M9B         Etobicoke      Martin Grove
19      M9B         Etobicoke  Princess Gardens

In [166]:
postuni=df3["Postcode"].unique()
postuni

array(['M3A', 'M4A', 'M5A', 'M6A', 'M7A', 'M9A', 'M1B', 'M3B', 'M4B',
       'M5B', 'M6B', 'M9B', 'M1C', 'M3C', 'M4C', 'M5C', 'M6C', 'M9C',
       'M1E', 'M4E', 'M5E', 'M6E', 'M1G', 'M4G', 'M5G', 'M6G', 'M1H',
       'M2H', 'M3H', 'M4H', 'M5H', 'M6H', 'M1J', 'M2J', 'M3J', 'M4J',
       'M5J', 'M6J', 'M1K', 'M2K', 'M3K', 'M4K', 'M5K', 'M6K', 'M1L',
       'M2L', 'M3L', 'M4L', 'M5L', 'M6L', 'M9L', 'M1M', 'M2M', 'M3M',
       'M4M', 'M5M', 'M6M', 'M9M', 'M1N', 'M2N', 'M3N', 'M4N', 'M5N',
       'M6N', 'M9N', 'M1P', 'M2P', 'M4P', 'M5P', 'M6P', 'M9P', 'M1R',
       'M2R', 'M4R', 'M5R', 'M6R', 'M7R', 'M9R', 'M1S', 'M4S', 'M5S',
       'M6S', 'M1T', 'M4T', 'M5T', 'M1V', 'M4V', 'M5V', 'M8V', 'M9V',
       'M1W', 'M4W', 'M5W', 'M8W', 'M9W', 'M1X', 'M4X', 'M5X', 'M8X',
       'M4Y', 'M7Y', 'M8Y', 'M8Z'], dtype=object)

In [266]:
df4=df3
df4

    Postcode           Borough             Neighbourhood
0        M3A        North York                 Parkwoods
1        M4A        North York          Victoria Village
2        M5A  Downtown Toronto              Harbourfront
3        M5A  Downtown Toronto               Regent Park
4        M6A        North York          Lawrence Heights
..       ...               ...                       ...
206      M8Z         Etobicoke  Kingsway Park South West
207      M8Z         Etobicoke                 Mimico NW
208      M8Z         Etobicoke        The Queensway West
209      M8Z         Etobicoke     Royal York South West
210      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [268]:
df4

    Postcode           Borough             Neighbourhood
0        M3A        North York                 Parkwoods
1        M4A        North York          Victoria Village
2        M5A  Downtown Toronto              Harbourfront
3        M5A  Downtown Toronto               Regent Park
4        M6A        North York          Lawrence Heights
..       ...               ...                       ...
206      M8Z         Etobicoke  Kingsway Park South West
207      M8Z         Etobicoke                 Mimico NW
208      M8Z         Etobicoke        The Queensway West
209      M8Z         Etobicoke     Royal York South West
210      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [269]:
df4.groupby(["Postcode","Borough"])
df4

    Postcode           Borough             Neighbourhood
0        M3A        North York                 Parkwoods
1        M4A        North York          Victoria Village
2        M5A  Downtown Toronto              Harbourfront
3        M5A  Downtown Toronto               Regent Park
4        M6A        North York          Lawrence Heights
..       ...               ...                       ...
206      M8Z         Etobicoke  Kingsway Park South West
207      M8Z         Etobicoke                 Mimico NW
208      M8Z         Etobicoke        The Queensway West
209      M8Z         Etobicoke     Royal York South West
210      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [271]:
df5=pd.DataFrame(df4.groupby(["Postcode","Borough"])["Neighbourhood"].apply(",".join))
df5

                                                          Neighbourhood
Postcode Borough
M1B      Scarborough                                      Rouge,Malvern
M1C      Scarborough               Highland Creek,Rouge Hill,Port Union
M1E      Scarborough                    Guildwood,Morningside,West Hill
M1G      Scarborough                                             Woburn
M1H      Scarborough                                          Cedarbrae
...                                                                 ...
M9N      York                                                    Weston
M9P      Etobicoke                                            Westmount
M9R      Etobicoke    Kingsview Village,Martin Grove Gardens,Richvie...
M9V      Etobicoke    Albion Gardens,Beaumond Heights,Humbergate,Jam...
M9W      Etobicoke                                            Northwest

[103 rows x 1 columns]

In [275]:
df5

                                                          Neighbourhood
Postcode Borough
M1B      Scarborough                                      Rouge,Malvern
M1C      Scarborough               Highland Creek,Rouge Hill,Port Union
M1E      Scarborough                    Guildwood,Morningside,West Hill
M1G      Scarborough                                             Woburn
M1H      Scarborough                                          Cedarbrae
...                                                                 ...
M9N      York                                                    Weston
M9P      Etobicoke                                            Westmount
M9R      Etobicoke    Kingsview Village,Martin Grove Gardens,Richvie...
M9V      Etobicoke    Albion Gardens,Beaumond Heights,Humbergate,Jam...
M9W      Etobicoke                                            Northwest

[103 rows x 1 columns]

In [276]:
df5.reset_index(level=['Postcode','Borough'],inplace=True)
df5

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                      Rouge,Malvern
1        M1C  Scarborough               Highland Creek,Rouge Hill,Port Union
2        M1E  Scarborough                    Guildwood,Morningside,West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village,Martin Grove Gardens,Richvie...
101      M9V    Etobicoke  Albion Gardens,Beaumond Heights,Humbergate,Jam...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [277]:
df5.head(50)

,Postcode,Borough,Neighbourhood
0,M1B,Scarborough,"Rouge,Malvern"
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union"
2,M1E,Scarborough,"Guildwood,Morningside,West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"East Birchmount Park,Ionview,Kennedy Park"
7,M1L,Scarborough,"Clairlea,Golden Mile,Oakridge"
8,M1M,Scarborough,"Cliffcrest,Cliffside,Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff,Cliffside West"
10,M1P,Scarborough,"Dorset Park,Scarborough Town Centre,Wexford He..."
11,M1R,Scarborough,"Maryvale,Wexford"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners,Sullivan,Tam O'Shanter"
14,M1V,Scarborough,"Agincourt North,L'Amoreaux East,Milliken,Steel..."
15,M1W,Scarborough,L'Amoreaux West
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview,Henry Farm,Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"Silver Hills,York Mills"
21,M2M,North York,"Newtonbrook,Willowdale"
22,M2N,North York,Willowdale South
23,M2P,North York,York Mills West
24,M2R,North York,Willowdale West
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills North
27,M3C,North York,"Flemingdon Park,Don Mills South"
28,M3H,North York,"Bathurst Manor,Downsview North,Wilson Heights"
29,M3J,North York,"Northwood Park,York University"
30,M3K,North York,"CFB Toronto,Downsview East"
31,M3L,North York,Downsview West
32,M3M,North York,Downsview Central
33,M3N,North York,Downsview Northwest
34,M4A,North York,Victoria Village
35,M4B,East York,"Woodbine Gardens,Parkview Hill"
36,M4C,East York,Woodbine Heights
37,M4E,East Toronto,The Beaches
38,M4G,East York,Leaside
39,M4H,East York,Thorncliffe Park
40,M4J,East York,East Toronto
41,M4K,East Toronto,"The Danforth West,Riverdale"
42,M4L,East Toronto,"The Beaches West,India Bazaar"
43,M4M,East Toronto,Studio District
44,M4N,Central Toronto,Lawrence Park
45,M4P,Central Toronto,Davisville North
46,M4R,Central Toronto,North Toronto West
47,M4S,Central Toronto,Davisville
48,M4T,Central Toronto,"Moore Park,Summerhill East"
49,M4V,Central Toronto,"Deer Park,Forest Hill SE,Rathnelly,South Hill,..."